// Alias file - Created 22/3/2021 by Amos Bordowitz

// IL-Core profiles
Alias: $ILPatient =                     http://fhir.health.gov.il/StructureDefinition/il-core-patient
Alias: $ILPractitioner =                http://fhir.health.gov.il/StructureDefinition/il-core-practitioner
Alias: $ILPractitionerRole =            http://fhir.health.gov.il/StructureDefinition/il-core-practitioner-role
Alias: $ILAddress =                     http://fhir.health.gov.il/StructureDefinition/il-core-address
Alias: $ILDosage =                      http://fhir.health.gov.il/StructureDefinition/il-core-dosage
Alias: $ILLocation =                    http://fhir.health.gov.il/StructureDefinition/il-core-location
Alias: $ILOrganization =                http://fhir.health.gov.il/StructureDefinition/il-core-organization
Alias: $ILCondition =                   http://fhir.health.gov.il/StructureDefinition/il-core-condition
Alias: $ILCoverageEligibilityRequest =  http://fhir.health.gov.il/StructureDefinition/il-core-coverage-eligibility-request
Alias: $ILCoverageEligibilityResponse = http://fhir.health.gov.il/StructureDefinition/il-core-coverage-eligibility-response
Alias: $ILDevice =                      http://fhir.health.gov.il/StructureDefinition/il-core-device
Alias: $ILDeviceDefinition =            http://fhir.health.gov.il/StructureDefinition/il-core-device-definition
Alias: $ILDocumentReference =           http://fhir.health.gov.il/StructureDefinition/il-core-document-reference
Alias: $ILMedicationRequest =           http://fhir.health.gov.il/StructureDefinition/il-core-medication-request
Alias: $ILObservation =                 http://fhir.health.gov.il/StructureDefinition/il-core-observation
Alias: $ILObservationLab =              http://fhir.health.gov.il/StructureDefinition/il-core-observation-lab
Alias: $ILMedia =                       http://fhir.health.gov.il/StructureDefinition/il-core-media
Alias: $ILQuestionnaireResponse =       http://fhir.health.gov.il/StructureDefinition/il-core-questionnaire-response
Alias: $ILServiceRequest =              http://fhir.health.gov.il/StructureDefinition/il-core-service-request
Alias: $ILDiagnosticReport =            http://fhir.health.gov.il/StructureDefinition/il-core-diagnostic-report
Alias: $ILEncounter =                   http://fhir.health.gov.il/StructureDefinition/il-core-encounter
Alias: $ILImagingStudy =                http://fhir.health.gov.il/StructureDefinition/il-core-imaging-study
Alias: $ILPlanDefinition =              http://fhir.health.gov.il/StructureDefinition/il-core-plan-definition
Alias: $ILProcedure =                   http://fhir.health.gov.il/StructureDefinition/il-core-procedure
Alias: $ILMedication =                  http://fhir.health.gov.il/StructureDefinition/il-core-medication
Alias: $ILRelatedPerson =               http://fhir.health.gov.il/StructureDefinition/il-core-related-person
Alias: $ILFamilyMemberHistory =         http://fhir.health.gov.il/StructureDefinition/il-core-family-member-history
Alias: $ILSpecimen =                    http://fhir.health.gov.il/StructureDefinition/il-core-specimen
Alias: $ILClaim =                       http://fhir.health.gov.il/StructureDefinition/il-core-claim
Alias: $ILAllergyIntolerance =          http://fhir.health.gov.il/StructureDefinition/il-core-allergy-intolerance
Alias: $ILGroup =                       http://fhir.health.gov.il/StructureDefinition/il-core-group
Alias: $ILImmunization =                http://fhir.health.gov.il/StructureDefinition/il-core-immunization
Alias: $ILImmunizationReactionObs =     http://fhir.health.gov.il/StructureDefinition/il-core-immunization-reaction-observation
 
// IDs & licenses
Alias: $il-id =                         http://fhir.health.gov.il/identifier/il-national-id
Alias: $pna-id =                        http://fhir.health.gov.il/identifier/pna-national-id
Alias: $id-type =                       http://terminology.hl7.org/CodeSystem/v2-0203
Alias: $legal-entity =                  http://fhir.health.gov.il/identifier/legal-entity
Alias: $moh-inst-symbol =               http://institutions.health.gov.il/Institutions
Alias: $enc =                           http://fhir.health.gov.il/identifier/encrypted-id-primary-moh
Alias: $moe-inst =                      http://fhir.health.gov.il/identifier/moe-institute-symbol
Alias: $practitioner-license-moh =      http://practitioners.health.gov.il/Practitioners
Alias: $practitioner-certificate =      http://practitioners.health.gov.il/practitioner-certificate 
Alias: $nurse-license-moh =             http://practitioners.health.gov.il/Nurses
Alias: $nurse-expertise =               http://fhir.health.gov.il/identifier/nurse-expertise 
Alias: $nurse-advanced-course =         http://fhir.health.gov.il/identifier/nurse-advanced-course
Alias: $practitioner-expertise =        http://fhir.health.gov.il/identifier/practitioner-expertise
Alias: $practitioner-instructor =       http://fhir.health.gov.il/identifier/practitioner-instructor 
Alias: $practitioner-license-molsa =    http://fhir.health.gov.il/identifier/molsa-socialworker-lic
Alias: $stat-area-id =                  http://fhir.health.gov.il/identifier/cbs-statistical-area

// Extensions - ILCore
Alias: $ext-ct =                        http://fhir.health.gov.il/StructureDefinition/ext-city-code
Alias: $ext-hmo =                       http://fhir.health.gov.il/StructureDefinition/ext-il-hmo
Alias: $ext-parent-name =               http://fhir.health.gov.il/StructureDefinition/ext-parent-name
Alias: $ext-procedure-reference =      http://fhir.health.gov.il/StructureDefinition/ext-procedure-reference
Alias: $ext-narcotic-medication =        http://fhir.health.gov.il/StructureDefinition/ext-narcotic-medication
Alias: $ext-admin-parent-name =         http://fhir.health.gov.il/StructureDefinition/ext-administrative-parent-name
Alias: $ext-patient-immigration =       http://fhir.health.gov.il/StructureDefinition/ext-patient-immigration
Alias: $ext-hebrew-date =               http://fhir.health.gov.il/StructureDefinition/ext-hebrew-date
Alias: $ext-reaction-duration =         http://fhir.health.gov.il/StructureDefinition/ext-reaction-duration
Alias: $ext-recorded-time =             http://fhir.health.gov.il/StructureDefinition/ext-recorded-time
Alias: $ext-event-occurrence-location = http://fhir.health.gov.il/StructureDefinition/ext-event-occurrence-location
Alias: $ext-allergy-intolerance-end   = http://fhir.health.gov.il/StructureDefinition/ext-allergy-intolerance-end
Alias: $ext-role =                      http://fhir.health.gov.il/StructureDefinition/ext-role
Alias: $ext-statistical-area =          http://fhir.health.gov.il/StructureDefinition/ext-statistical-area
Alias: $ext-qualification-practice =    http://fhir.health.gov.il/StructureDefinition/ext-qualification-practice

// Extensions - external
Alias: $ext-birth-place =               http://hl7.org/fhir/StructureDefinition/patient-birthPlace
Alias: $street-name =                   http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName
Alias: $house-num =                     http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber
Alias: $bldng-num-suffx =               http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-buildingNumberSuffix
Alias: $unit-id =                       http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-unitID
Alias: $post-box =                      http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-postBox
Alias: $geolocation =                   http://hl7.org/fhir/StructureDefinition/geolocation
Alias: $us-core-birth-sex =             http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex
Alias: $data-absent-reason =            http://hl7.org/fhir/StructureDefinition/data-absent-reason
Alias: $relative-date =                 http://hl7.org/fhir/StructureDefinition/relative-date


// Codesystems - ILCore
Alias: $icd9-il =                       http://fhir.health.gov.il/cs/icd9il
Alias: $icd9-il-code-types =            http://fhir.health.gov.il/cs/icd9il-code-types
Alias: $city-code =                     http://fhir.health.gov.il/cs/city-symbol
Alias: $course-of-therapy =             http://fhir.health.gov.il/cs/course-of-therapy
Alias: $payer =                         http://fhir.health.gov.il/cs/paying-entity-moh
Alias: $pp-uri =                        http://fhir.health.gov.il/cs/passport-uri
Alias: $hebrew-date-day =               http://fhir.health.gov.il/cs/hebrew-date-day
Alias: $hebrew-date-month =             http://fhir.health.gov.il/cs/hebrew-date-month
Alias: $practitioner-profession-moh =   http://fhir.health.gov.il/cs/practitioner-profession-moh
Alias: $practitioner-profession-molsa = http://fhir.health.gov.il/cs/practitioner-profession-molsa
Alias: $department-type-moh =           http://fhir.health.gov.il/cs/department-type-moh
Alias: $institution-type-moh =          http://fhir.health.gov.il/cs/institution-type-moh
Alias: $practitioner-expertise-moh =    http://fhir.health.gov.il/cs/practitioner-expertise-moh
Alias: $practitioner-education =        http://fhir.health.gov.il/cs/practitioner-education-moh
Alias: $practitioner-advanced-course-moh = http://fhir.health.gov.il/cs/practitioner-advanced-course-moh
Alias: $practitioner-education-type =   http://fhir.health.gov.il/cs/practitioner-education-type-moh
Alias: $pract-certificate-type-moh =    http://fhir.health.gov.il/cs/practitioner-certificate-type-moh
Alias: $pract-certificate-type-molsa =  http://fhir.health.gov.il/cs/practitioner-certificate-type-molsa
Alias: $medical-service-code-moh =      http://fhir.health.gov.il/cs/medical-service-moh
Alias: $not-performed-reason =          http://fhir.health.gov.il/cs/il-core-not-performed-reason

// Codesystems - external
// Alias: $medical-service-code =       http://www.ama-assn.org/go/cpt
Alias: $loinc =                         http://loinc.org
Alias: $sct =                           http://snomed.info/sct
Alias: $dar =                           http://terminology.hl7.org/CodeSystem/data-absent-reason
Alias: $v3-ObservationValue =           http://terminology.hl7.org/CodeSystem/v3-ObservationValue
Alias: $clinicalStatus =                http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical
Alias: $verificationStatus =            http://terminology.hl7.org/CodeSystem/allergyintolerance-verification
Alias: $v2-0131 =                       http://terminology.hl7.org/CodeSystem/v2-0131
Alias: $v3-RoleCode =                   http://terminology.hl7.org/CodeSystem/v3-RoleCode
Alias: $age-units =                     http://hl7.org/fhir/ValueSet/age-units
Alias: $moh-qualification =             http://qualification.health.gov.il
Alias: $icd9-cm =                       http://hl7.org/fhir/sid/icd-9-cm
Alias: $cvx =                           http://hl7.org/fhir/sid/cvx
Alias: $atc =                           http://www.whocc.no/atc
Alias: $yarpa-medication-code =         http://yarpa.co.il/catalog
Alias: $moh-medication-code =           http://israeldrugs.health.gov.il
Alias: $country-codes  =                urn:iso:std:iso:3166
Alias: $urn =                           urn:ietf:rfc:3986

// value-sets
Alias: $vs-hmo =                        http://fhir.health.gov.il/ValueSet/israel-hmo
Alias: $vs-city-code =                  http://fhir.health.gov.il/ValueSet/city-symbol
Alias: $vs-pp-uri =                     http://fhir.health.gov.il/ValueSet/passport-uri
Alias: $vs-practitioner-profession-moh =  http://fhir.health.gov.il/ValueSet/practitioner-profession-moh
Alias: $vs-practitioner-profession-molsa = http://fhir.health.gov.il/ValueSet/practitioner-profession-molsa
Alias: $vs-practitioner-advanced-course = http://fhir.health.gov.il/ValueSet/practitioner-advanced-course-moh
Alias: $vs-practitioner-nurse-profession = http://fhir.health.gov.il/ValueSet/practitioner-nurse-profession-moh
Alias: $vs-practitioner-expertise =     http://fhir.health.gov.il/ValueSet/practitioner-expertise-moh
Alias: $vs-pract-certificate-type =     http://fhir.health.gov.il/ValueSet/practitioner-certificate-type
Alias: $vs-practitioner-education =     http://fhir.health.gov.il/ValueSet/practitioner-education-moh
Alias: $vs-institution-type-moh =       http://fhir.health.gov.il/ValueSet/institution-type-moh
Alias: $vs-organization-type =          http://fhir.health.gov.il/ValueSet/organization-type
Alias: $vs-department-type-moh =        http://fhir.health.gov.il/ValueSet/department-type-moh
Alias: $vs-medical-service-code =       http://fhir.health.gov.il/ValueSet/medical-service-code
Alias: $vs-medical-service-moh =        http://fhir.health.gov.il/ValueSet/medical-service-moh
Alias: $vs-statistical-area-uri =       http://fhir.health.gov.il/ValueSet/statistical-area-uri
Alias: $vs-patient-relationship-type =  http://fhir.health.gov.il/ValueSet/patient-relationship-type
Alias: $vs-il-core-allergy-intolerance-code = http://fhir.health.gov.il/ValueSet/il-core-allergy-intolerance-code
Alias: $vs-il-core-allergy-intolerance-end-reason = http://fhir.health.gov.il/ValueSet/il-core-allergy-intolerance-end-reason
Alias: $vs-il-core-condition-code =     http://fhir.health.gov.il/ValueSet/il-core-condition-code
Alias: $vs-il-core-medication-allergy-intolerance = http://fhir.health.gov.il/ValueSet/il-core-medication-allergyIntolerance
Alias: $vs-il-core-food-allergy-intolerance = http://fhir.health.gov.il/ValueSet/il-core-food-allergyIntolerance
Alias: $vs-il-core-environmental-allergy-intolerance = http://fhir.health.gov.il/ValueSet/il-core-environmental-allergyIntolerance
Alias: $vs-il-core-biological-substance = http://fhir.health.gov.il/ValueSet/il-core-biological-substance
Alias: $vs-il-core-environmental-substance = http://fhir.health.gov.il/ValueSet/il-core-environmental-substance
Alias: $vs-il-core-food-substance =     http://fhir.health.gov.il/ValueSet/il-core-food-substance
Alias: $vs-il-core-medication-substance = http://fhir.health.gov.il/ValueSet/il-core-medication-substance
Alias: $vs-il-core-medication-request-course-of-therapy = http://fhir.health.gov.il/ValueSet/il-core-medication-request-course-of-therapy
Alias: $vs-il-core-medication-request-category = http://fhir.health.gov.il/ValueSet/il-core-medication-request-category
Alias: $vs-il-core-manifestation =      http://fhir.health.gov.il/ValueSet/il-core-manifestation
Alias: $vs-il-core-medication-code =    http://fhir.health.gov.il/ValueSet/il-core-medication-code
Alias: $vs-il-core-observation-value =  http://fhir.health.gov.il/ValueSet/il-core-observation-value
Alias: $vs-il-core-observation-code =   http://fhir.health.gov.il/ValueSet/il-core-observation-code
Alias: $vs-il-core-substance =          http://fhir.health.gov.il/ValueSet/il-core-substance
Alias: $vs-il-core-service-category =   http://fhir.health.gov.il/ValueSet/il-core-service-category
Alias: $vs-il-core-procedure-code =     http://fhir.health.gov.il/ValueSet/il-core-procedure-code
Alias: $vs-il-core-procedure-reason =   http://fhir.health.gov.il/ValueSet/il-core-procedure-reason
Alias: $vs-il-core-route-code =         http://fhir.health.gov.il/ValueSet/il-core-route-code
Alias: $vs-il-core-units-of-measure =   http://fhir.health.gov.il/ValueSet/il-core-units-of-measure
Alias: $vs-hebrew-date-day =            http://fhir.health.gov.il/ValueSet/hebrew-date-day
Alias: $vs-hebrew-date-month =          http://fhir.health.gov.il/ValueSet/hebrew-date-month
Alias: $vs-il-core-condition-category = http://fhir.health.gov.il/ValueSet/il-core-condition-category
Alias: $vs-il-core-parent-name-role =   http://fhir.health.gov.il/ValueSet/il-core-parent-name-role
Alias: $vs-icd9-cm-procedures =         http://fhir.health.gov.il/ValueSet/icd9-cm-procedures
Alias: $vs-icd9-cm-diagnoses =          http://fhir.health.gov.il/ValueSet/icd9-cm-diagnoses
Alias: $vs-icd9-il-procedures =         http://fhir.health.gov.il/ValueSet/icd9il-procedures
Alias: $vs-icd9-il-diagnoses =          http://fhir.health.gov.il/ValueSet/icd9il-diagnoses
Alias: $vs-immun-body-site =            http://fhir.health.gov.il/ValueSet/immunization-body-site
Alias: $vs-reason-not-done =            http://fhir.health.gov.il/ValueSet/reason-not-done
Alias: $vs-immunization-side-effects =  http://fhir.health.gov.il/ValueSet/immunization-side-effect
Alias: $bodySite =                      http://hl7.org/fhir/ValueSet/body-site
Alias: $vs-jurisdiction =               http://hl7.org/fhir/ValueSet/jurisdiction
Alias: $vs-vaccine-code =               http://fhir.health.gov.il/ValueSet/vaccine-code
Alias: $vs-vaccine-product-code =       http://fhir.health.gov.il/ValueSet/vaccine-product-code
Alias: $vs-target-disease =             http://fhir.health.gov.il/ValueSet/target-disease
Alias: $vs-moh-medication-code =        http://fhir.health.gov.il/ValueSet/moh-medication-code
Alias: $vs-yarpa-medication-code =      http://fhir.health.gov.il/ValueSet/yarpa-medication-code
Alias: $vs-not-performed-reason =       http://fhir.health.gov.il/ValueSet/il-core-not-performed-reason

// required for Conition:
Alias: $condition-clinical =            http://terminology.hl7.org/CodeSystem/condition-clinical
Alias: $condition-ver-status =          http://terminology.hl7.org/CodeSystem/condition-ver-status
Alias: $condition-category =            http://terminology.hl7.org/CodeSystem/condition-category

// TEMP ///////////////////
Alias: $us-core-patient = http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient
Alias: $us-core-practitioner = http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitioner
Alias: $us-core-organization = http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization
Alias: $us-core-practitionerrole = http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitionerrole
Alias: $us-core-relatedperson = http://hl7.org/fhir/us/core/StructureDefinition/us-core-relatedperson
Alias: $us-core-encounter = http://hl7.org/fhir/us/core/StructureDefinition/us-core-encounter
Alias: $us-core-documentreference-type = http://hl7.org/fhir/us/core/ValueSet/us-core-documentreference-type
Alias: $us-core-documentreference-category = http://hl7.org/fhir/us/core/ValueSet/us-core-documentreference-category

